### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Plozano94** [simracingtools/teamtactics#8]
Hi Robert,

I'm a Machine Learning Engineer, and also an iracing player and I was looking for some project like this to contribute in the client or in the server side. I could help with any backend task. I couldn't find any email to reach you. Could you tell me if you are open to talk a bit about your project?

best regards

**Comment by robbyb67** [comment]
Hi,

thx for contacting me. I would indeed appreciate some help/contribution to the project. Perhaps we could schedule a meeting (google?) to talk a bit about the project, it's current state and your interest in it. You can reach me per mail [rbausdorf@gmail.com](mailto:rbausdorf@gmail.com)

Cheers - Robert
